version: 2
updates:
  - package-ecosystem: "nuget"
    directory: /
    schedule:
      interval: daily
      time: "12:16"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]